app/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('post/new/', FieldCreateView.as_view(), name='field_new'), 
    path('', post_list, name='posts_list_url'),
    path('list/',field_list, name="field_list"),
    path('field/<int:pk>/', FieldDetailView.as_view(), name='field_detail'), 
]

apps/users/urls.py
from django.urls import path
from .views import (
    RegistrationView, ActivationView, CabinetView, ProfileEditView, CustomersList
)

app_name = 'users'

urlpatterns = [
    path('registration/', RegistrationView.as_view(), name='registration'),
    path(
        'activate/<str:uidb64>/<str:token>/<str:type_of_user>/',
        ActivationView.as_view(),
        name='activation'
    ),
    path('cabinet/', CabinetView.as_view(), name='cabinet'),
    path('cabinet/edit/', ProfileEditView.as_view(), name='edit'),
    path('customers-list/', CustomersList.as_view(), name='customers_list'),
]

apps/website/urls.py
from django.urls import path
from .views import IndexView

app_name = 'website'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import  settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')), 
    path('accounts/', include('authtools.urls')),
    path('accounts/', include('apps.users.urls')),
    path('website/', include('apps.website.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/shared/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <title>{% block title %} {% endblock %}</title>
</head>
<body data-media-url="{% get_media_prefix %}">
        <div class="row">
                <div class="col-xs-12 col-lg-12">
        <header>
            <nav>
                <ul>
                    <li><a href="{% url "website:index" %}">Home</a></li>
                    <li><a href="#">About</a></li>
                    <li><a href="#">Gallery</a></li>
                    {% if user.is_authenticated %}
                    <li><a href="{% url 'users:cabinet' %}">Cabinet</a></li>
                    <li><a href="{% url 'logout' %}">Logout</a></li>
                    {% else %}
                    <li><a href="{% url 'users:registration' %}">Register</a></li>
                    <li><a href="{% url "login" %}">Login</a></li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        <div class="container">
        {% block content %}
        {% endblock %}
        </div>
        <p></p>
        <footer>This is footer</footer>
        </div>
    </div>
    <script>
        console.log('Hi!')
    </script>
    <script src="{% static "js/main.js" %}" type="text/javascript"></script>
</body>
</html>